"""Project-wide constants."""

TOOL_TIMEOUT_SECONDS: float = 90.0
PERSON_PROFILE_TOOL_TIMEOUT_SECONDS: float = 300.0
MANUAL_LOGIN_TIMEOUT_MS: int = 540000
MANUAL_LOGIN_TIMEOUT_MINUTES: int = MANUAL_LOGIN_TIMEOUT_MS // 60000
